/** Generated by `scripts/pullThemes.ts` */

export const themes = [{
    label: 'light',
    uiTheme: 'vs',
    path: './akamud.vscode-theme-onelight.atom-one-light.json',
    // @ts-expect-error no types
    register: async () => (await import('./akamud.vscode-theme-onelight.atom-one-light?raw')).default
  },{
    label: 'dark',
    uiTheme: 'vs-dark',
    path: './kricsleo.gentle-clean.gentle-clean-vitesse.json',
    // @ts-expect-error no types
    register: async () => (await import('./kricsleo.gentle-clean.gentle-clean-vitesse.json?raw')).default
  },
]